blueprint:
  name: Scene Cycle Button
  description:
    "Switch between multiple scenes on Philips Hue Smart button clicks.
    Supports long press, double press, and triple press actions as well."
  domain: automation
  author: Tim-Jonas Schwarz
  input:
    button:
      name: Button
      description: This button will be used to cycle through the scenes.
      selector:
        device:
          entity:
            - domain:
                - sensor
              device_class:
                - battery
              integration: hue
            - domain:
                - sensor
              device_class:
                - battery
              integration: zha
          filter:
            - integration: hue
              model: Hue Smart button (ROM001)
              manufacturer: Signify Netherlands B.V.
            - integration: hue
              model: Hue Smart button (ROM001)
              manufacturer: Philips
            - integration: zha
              model: ROM001
              manufacturer: Signify Netherlands B.V.
            - integration: zha
              model: ROM001
              manufacturer: Philips
          multiple: false
    target_area:
      name: Area
      description: This area will be controlled by the button.
      selector:
        area:
          multiple: false
    scene_state_counter_helper:
      name: Scene state counter helper
      description: Define a counter helper which stores the number of clicks in a row.
      selector:
        entity:
          filter:
            - domain: counter
    scenes_default:
      name: Scenes
      description: Define the scenes to cycle through on button press.
      selector:
        entity:
          filter:
            - domain: scene
          multiple: true
    button_press_timeout:
      name: Button press timeout
      description: The time window in which a button press after a previous button one switches to the next scene.
      selector:
        duration:
      default:
        hours: 0
        minutes: 0
        seconds: 3
    action_long_press:
      name: Action on long button press
      description: Define an action to perform when button is double-pressed.
      default: Dim lights
      selector:
        select:
          options:
            - Dim lights
            - Turn off all lights
    action_double_press:
      name: Action on double button press (optional)
      description: Define an action to perform when button is double-pressed.
      default: []
      selector:
        action:
    action_triple_press:
      name: Action on triple button press (optional)
      description: Define an action to perform when button is triple-pressed.
      default: []
      selector:
        action:
trigger:
  - device_id: !input button
    domain: zha
    platform: device
    type: remote_button_short_release
    subtype: turn_on
    id: Single press
  - device_id: !input button
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: turn_on
    id: Continuously pressed
  - device_id: !input button
    domain: zha
    platform: device
    type: remote_button_double_press
    subtype: turn_on
    id: Double press
  - device_id: !input button
    domain: zha
    platform: device
    type: remote_button_triple_press
    subtype: turn_on
    id: Triple press
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - Single press
        sequence:
          - if:
              - condition: or
                conditions:
                  - condition: template
                    value_template: "{{ (now().timestamp() - this.attributes.last_triggered.timestamp()) < button_press_timeout_seconds }}"
                    enabled: true
                    alias: Check if time since last triggered is < than predefined value
                  - condition: template
                    value_template: "{{ is_light_off }}"
                    alias: Check if target lights are off
            then:
              - if:
                  - condition: template
                    value_template: "{{ is_light_off }}"
                    alias: Check if target lights are off
                then:
                  - service: scene.turn_on
                    target:
                      entity_id: "{{ scenes_default[0] }}"
                    data:
                      transition: 0
                  - service: counter.set_value
                    target:
                      entity_id: "{{ scene_state_counter_helper }}"
                    data:
                      value: 1
                else:
                  - service: scene.turn_on
                    target:
                      entity_id: "{{ next_scene }}"
                    data:
                      transition: 0
                  - service: counter.increment
                    target:
                      entity_id: "{{ scene_state_counter_helper }}"
            else:
              - service: light.turn_off
                target:
                  area_id: "{{ target_area }}"
      - conditions:
          - condition: trigger
            id:
              - Continuously pressed
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ action_long_press == 'Turn off all lights' }}"
                sequence:
                  - service: light.turn_off
                    entity_id: all
                    alias: Turn off all lights
                    data:
                      transition: 0.1
              - conditions:
                  - condition: template
                    value_template: "{{ action_long_press == 'Dim lights' }}"
                sequence:
                  - if:
                      - condition: template
                        value_template: "{{ brightness > 253 }}"
                    then:
                      - service: light.turn_off
                        data:
                          transition: 0
                        target:
                          area_id: "{{ target_area }}"
                      - delay:
                          hours: 0
                          minutes: 0
                          seconds: 0
                          milliseconds: 100
                      - service: light.turn_on
                        data:
                          transition: 0
                        target:
                          area_id: "{{ target_area }}"
                    else:
                      - repeat:
                          for_each: "{{ target_lights }}"
                          sequence:
                            service: light.turn_on
                            data_template:
                              entity_id: "{{ repeat.item }}"
                              transition: >-
                                {% if states(repeat.item) == 'off' %}
                                  0
                                {% else %}
                                  0.7
                                {% endif %}
                              brightness: >-
                                {% set entity_brightness = state_attr(repeat.item, 'brightness') %}
                                {% if not entity_brightness == None %}
                                  {{ [entity_brightness + 25, 255] | min }}
                                {% else %}
                                  25
                                {% endif %}
      - conditions:
          - condition: trigger
            id:
              - Double press
        sequence: !input action_double_press
      - conditions:
          - condition: trigger
            id:
              - Triple press
        sequence: !input action_triple_press
mode: restart
variables:
  target_area: !input "target_area"
  scene_state_counter_helper: !input "scene_state_counter_helper"
  scenes_default: !input "scenes_default"
  action_long_press: !input "action_long_press"
  button_press_timeout: !input "button_press_timeout"
  scene_state_counter_value: "{{ states(scene_state_counter_helper) | int }}"
  next_scene: "{{ scenes_default[scene_state_counter_value % scenes_default|length] }}"
  target_lights: "{{ area_entities(target_area) | select('match', '^light\\..+') | list }}"
  target_lights_on: "{{ expand(target_lights) | selectattr('state', 'eq', 'on') | list }}"
  is_light_off: "{{ target_lights_on | count == 0 }}"
  brightness: "{{ target_lights | map('state_attr', 'brightness') | reject('==', None) | list | average(0) | round | int }}"
  button_press_timeout_seconds: "{{ [button_press_timeout.hours * 3600, button_press_timeout.minutes * 60, button_press_timeout.seconds] | sum }}"
